services:  
  mainnode:
    container_name: mainnode
    build:
      context: .
      dockerfile: Dockerfile
      target: mainnode-runtime
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATANODE_COUNT: ${DATANODE_COUNT}
    ports:
      - "8080:8080"
  datanode:
    container_name: datanode
    build:
      context: .
      dockerfile: Dockerfile
      target: datanode-runtime
    environment:
      MAINNODE_URL: ${MAINNODE_URL}