services:
  mainnode:
    container_name: mainnode
    build:
      context: .
      dockerfile: Dockerfile
      target: mainnode-runtime
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATANODE_COUNT: ${DATANODE_COUNT}
    restart: always
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8080 || exit 1"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 5s
  datanode1:
    container_name: datanode1
    build:
      context: .
      dockerfile: Dockerfile
      target: datanode-runtime
    environment:
      MAINNODE_URL: ${MAINNODE_URL}
      SELF_URL: datanode1:5000
      ROOT_DATA_FOLDER: ${ROOT_DATA_FOLDER}
      LISTEN_PORT: 5000
    depends_on:
      mainnode:
        condition: service_healthy
    tmpfs:
      - /data:size=1G
  datanode2:
    container_name: datanode2
    build:
      context: .
      dockerfile: Dockerfile
      target: datanode-runtime
    environment:
      MAINNODE_URL: ${MAINNODE_URL}
      SELF_URL: datanode2:5001
      ROOT_DATA_FOLDER: ${ROOT_DATA_FOLDER}
      LISTEN_PORT: 5001
    depends_on:
      mainnode:
        condition: service_healthy
    tmpfs:
      - /data:size=1G
  datanode3:
    container_name: datanode3
    build:
      context: .
      dockerfile: Dockerfile
      target: datanode-runtime
    environment:
      MAINNODE_URL: ${MAINNODE_URL}
      SELF_URL: datanode2:5002
      ROOT_DATA_FOLDER: ${ROOT_DATA_FOLDER}
      LISTEN_PORT: 5002
    depends_on:
      mainnode:
        condition: service_healthy
    tmpfs:
      - /data:size=1G