services:
  postgres:
    image: postgres:latest
    container_name: metadata_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:  ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  mainnode:
    container_name: mainnode
    build:
      context: .
      dockerfile: Dockerfile
      target: mainnode-runtime
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATANODE_COUNT: ${DATANODE_COUNT}
    ports:
      - "8080:8080"
  datanode:
    container_name: datanode
    build:
      context: .
      dockerfile: Dockerfile
      target: datanode-runtime
    environment:
      MAINNODE_URL: ${MAINNODE_URL}