// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/mainnode_service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MainNodeService_Register_FullMethodName = "/MainNodeService/Register"
)

// MainNodeServiceClient is the client API for MainNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MainNodeServiceClient interface {
	Register(ctx context.Context, in *DataNodeInfo, opts ...grpc.CallOption) (*RegisterReply, error)
}

type mainNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMainNodeServiceClient(cc grpc.ClientConnInterface) MainNodeServiceClient {
	return &mainNodeServiceClient{cc}
}

func (c *mainNodeServiceClient) Register(ctx context.Context, in *DataNodeInfo, opts ...grpc.CallOption) (*RegisterReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterReply)
	err := c.cc.Invoke(ctx, MainNodeService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MainNodeServiceServer is the server API for MainNodeService service.
// All implementations must embed UnimplementedMainNodeServiceServer
// for forward compatibility.
type MainNodeServiceServer interface {
	Register(context.Context, *DataNodeInfo) (*RegisterReply, error)
	mustEmbedUnimplementedMainNodeServiceServer()
}

// UnimplementedMainNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMainNodeServiceServer struct{}

func (UnimplementedMainNodeServiceServer) Register(context.Context, *DataNodeInfo) (*RegisterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedMainNodeServiceServer) mustEmbedUnimplementedMainNodeServiceServer() {}
func (UnimplementedMainNodeServiceServer) testEmbeddedByValue()                         {}

// UnsafeMainNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MainNodeServiceServer will
// result in compilation errors.
type UnsafeMainNodeServiceServer interface {
	mustEmbedUnimplementedMainNodeServiceServer()
}

func RegisterMainNodeServiceServer(s grpc.ServiceRegistrar, srv MainNodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedMainNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MainNodeService_ServiceDesc, srv)
}

func _MainNodeService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataNodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainNodeServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainNodeService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainNodeServiceServer).Register(ctx, req.(*DataNodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// MainNodeService_ServiceDesc is the grpc.ServiceDesc for MainNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MainNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MainNodeService",
	HandlerType: (*MainNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _MainNodeService_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mainnode_service.proto",
}
