// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: heart_beat_service.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkIDs      []string               `protobuf:"bytes,1,rep,name=chunkIDs,proto3" json:"chunkIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_heart_beat_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_heart_beat_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_heart_beat_service_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetChunkIDs() []string {
	if x != nil {
		return x.ChunkIDs
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_heart_beat_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heart_beat_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_heart_beat_service_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_heart_beat_service_proto protoreflect.FileDescriptor

const file_heart_beat_service_proto_rawDesc = "" +
	"\n" +
	"\x18heart_beat_service.proto\".\n" +
	"\x10HeartbeatRequest\x12\x1a\n" +
	"\bchunkIDs\x18\x01 \x03(\tR\bchunkIDs\"+\n" +
	"\x11HeartbeatResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2F\n" +
	"\x10HeartBeatService\x122\n" +
	"\tHeartbeat\x12\x11.HeartbeatRequest\x1a\x12.HeartbeatResponseB+Z)github.com/vignesh-j-shetty/GoDFS/pkg/rpcb\x06proto3"

var (
	file_heart_beat_service_proto_rawDescOnce sync.Once
	file_heart_beat_service_proto_rawDescData []byte
)

func file_heart_beat_service_proto_rawDescGZIP() []byte {
	file_heart_beat_service_proto_rawDescOnce.Do(func() {
		file_heart_beat_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_heart_beat_service_proto_rawDesc), len(file_heart_beat_service_proto_rawDesc)))
	})
	return file_heart_beat_service_proto_rawDescData
}

var file_heart_beat_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_heart_beat_service_proto_goTypes = []any{
	(*HeartbeatRequest)(nil),  // 0: HeartbeatRequest
	(*HeartbeatResponse)(nil), // 1: HeartbeatResponse
}
var file_heart_beat_service_proto_depIdxs = []int32{
	0, // 0: HeartBeatService.Heartbeat:input_type -> HeartbeatRequest
	1, // 1: HeartBeatService.Heartbeat:output_type -> HeartbeatResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_heart_beat_service_proto_init() }
func file_heart_beat_service_proto_init() {
	if File_heart_beat_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_heart_beat_service_proto_rawDesc), len(file_heart_beat_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_heart_beat_service_proto_goTypes,
		DependencyIndexes: file_heart_beat_service_proto_depIdxs,
		MessageInfos:      file_heart_beat_service_proto_msgTypes,
	}.Build()
	File_heart_beat_service_proto = out.File
	file_heart_beat_service_proto_goTypes = nil
	file_heart_beat_service_proto_depIdxs = nil
}
