// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/metadataserver_service.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetaDataService_Connect_FullMethodName = "/MetaDataService/Connect"
)

// MetaDataServiceClient is the client API for MetaDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetaDataServiceClient interface {
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectReply, error)
}

type metaDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetaDataServiceClient(cc grpc.ClientConnInterface) MetaDataServiceClient {
	return &metaDataServiceClient{cc}
}

func (c *metaDataServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectReply)
	err := c.cc.Invoke(ctx, MetaDataService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaDataServiceServer is the server API for MetaDataService service.
// All implementations must embed UnimplementedMetaDataServiceServer
// for forward compatibility.
type MetaDataServiceServer interface {
	Connect(context.Context, *ConnectRequest) (*ConnectReply, error)
	mustEmbedUnimplementedMetaDataServiceServer()
}

// UnimplementedMetaDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetaDataServiceServer struct{}

func (UnimplementedMetaDataServiceServer) Connect(context.Context, *ConnectRequest) (*ConnectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedMetaDataServiceServer) mustEmbedUnimplementedMetaDataServiceServer() {}
func (UnimplementedMetaDataServiceServer) testEmbeddedByValue()                         {}

// UnsafeMetaDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetaDataServiceServer will
// result in compilation errors.
type UnsafeMetaDataServiceServer interface {
	mustEmbedUnimplementedMetaDataServiceServer()
}

func RegisterMetaDataServiceServer(s grpc.ServiceRegistrar, srv MetaDataServiceServer) {
	// If the following call pancis, it indicates UnimplementedMetaDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetaDataService_ServiceDesc, srv)
}

func _MetaDataService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaDataServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaDataService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaDataServiceServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetaDataService_ServiceDesc is the grpc.ServiceDesc for MetaDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetaDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MetaDataService",
	HandlerType: (*MetaDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _MetaDataService_Connect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/metadataserver_service.proto",
}
