// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/metadataserver_service.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChunkServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	RpcEndpoint   string                 `protobuf:"bytes,2,opt,name=rpc_endpoint,json=rpcEndpoint,proto3" json:"rpc_endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkServerInfo) Reset() {
	*x = ChunkServerInfo{}
	mi := &file_proto_metadataserver_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkServerInfo) ProtoMessage() {}

func (x *ChunkServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadataserver_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkServerInfo.ProtoReflect.Descriptor instead.
func (*ChunkServerInfo) Descriptor() ([]byte, []int) {
	return file_proto_metadataserver_service_proto_rawDescGZIP(), []int{0}
}

func (x *ChunkServerInfo) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ChunkServerInfo) GetRpcEndpoint() string {
	if x != nil {
		return x.RpcEndpoint
	}
	return ""
}

type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_proto_metadataserver_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadataserver_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_proto_metadataserver_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisterReply) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_proto_metadataserver_service_proto protoreflect.FileDescriptor

const file_proto_metadataserver_service_proto_rawDesc = "" +
	"\n" +
	"\"proto/metadataserver_service.proto\"Q\n" +
	"\x0fChunkServerInfo\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12!\n" +
	"\frpc_endpoint\x18\x02 \x01(\tR\vrpcEndpoint\"D\n" +
	"\rRegisterReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg2A\n" +
	"\x0fMetaDataService\x12.\n" +
	"\bRegister\x12\x10.ChunkServerInfo\x1a\x0e.RegisterReply\"\x00B+Z)github.com/vignesh-j-shetty/GoDFS/pkg/rpcb\x06proto3"

var (
	file_proto_metadataserver_service_proto_rawDescOnce sync.Once
	file_proto_metadataserver_service_proto_rawDescData []byte
)

func file_proto_metadataserver_service_proto_rawDescGZIP() []byte {
	file_proto_metadataserver_service_proto_rawDescOnce.Do(func() {
		file_proto_metadataserver_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metadataserver_service_proto_rawDesc), len(file_proto_metadataserver_service_proto_rawDesc)))
	})
	return file_proto_metadataserver_service_proto_rawDescData
}

var file_proto_metadataserver_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_metadataserver_service_proto_goTypes = []any{
	(*ChunkServerInfo)(nil), // 0: ChunkServerInfo
	(*RegisterReply)(nil),   // 1: RegisterReply
}
var file_proto_metadataserver_service_proto_depIdxs = []int32{
	0, // 0: MetaDataService.Register:input_type -> ChunkServerInfo
	1, // 1: MetaDataService.Register:output_type -> RegisterReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_metadataserver_service_proto_init() }
func file_proto_metadataserver_service_proto_init() {
	if File_proto_metadataserver_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metadataserver_service_proto_rawDesc), len(file_proto_metadataserver_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metadataserver_service_proto_goTypes,
		DependencyIndexes: file_proto_metadataserver_service_proto_depIdxs,
		MessageInfos:      file_proto_metadataserver_service_proto_msgTypes,
	}.Build()
	File_proto_metadataserver_service_proto = out.File
	file_proto_metadataserver_service_proto_goTypes = nil
	file_proto_metadataserver_service_proto_depIdxs = nil
}
