DO$$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'server_role') THEN
    CREATE TYPE server_role AS ENUM ('PRIMARY', 'REPLICA');
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS CHUNK_SERVER (
  SERVER_ID VARCHAR(36) PRIMARY KEY,
  RPC_ADDR VARCHAR(65) NOT NULL,
  ROLE server_role NOT NULL DEFAULT 'PRIMARY',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);
