DO$$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'SERVER_ROLE_TYPE') THEN
    CREATE TYPE server_role AS ENUM ('PRIMARY', 'REPLICA');
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS CHUNK_SERVER (
  SERVER_ID VARCHAR(36) PRIMARY KEY,
  RPC_ENDPOINT VARCHAR(65) NOT NULL,
  ROLE SERVER_ROLE_TYPE NOT NULL DEFAULT 'PRIMARY',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);
